### ISSUE TITLE
submitting via the API causes an exception

### ISSUE THREAD

**Issue by justcool393** [themotte/rDrama#512]
```
themotte    | [2023-02-13 01:31:33,400] ERROR in app: Exception on /comment [POST]
themotte    | Traceback (most recent call last):
themotte    |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
themotte    |     response = self.full_dispatch_request()
themotte    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
themotte    |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1822, in full_dispatch_request
themotte    |     rv = self.handle_user_exception(e)
themotte    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
themotte    |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
themotte    |     rv = self.dispatch_request()
themotte    |          ^^^^^^^^^^^^^^^^^^^^^^^
themotte    |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
themotte    |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
themotte    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
themotte    |   File "/usr/local/lib/python3.11/site-packages/flask_limiter/extension.py", line 1152, in __inner
themotte    |     R, flask.current_app.ensure_sync(cast(Callable[P, R], obj))(*a, **k)
themotte    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
themotte    |   File "/service/files/helpers/wrappers.py", line 109, in wrapper
themotte    |     return make_response(f(*args, v=v, **kwargs))
themotte    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
themotte    |   File "/usr/local/lib/python3.11/site-packages/flask/helpers.py", line 209, in make_response
themotte    |     return current_app.make_response(args)  # type: ignore
themotte    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
themotte    |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2153, in make_response
themotte    |     rv = self.json.response(rv)
themotte    |          ^^^^^^^^^^^^^^^^^^^^^^
themotte    |   File "/usr/local/lib/python3.11/site-packages/flask/json/provider.py", line 309, in response
themotte    |     f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
themotte    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
themotte    |   File "/usr/local/lib/python3.11/site-packages/flask/json/provider.py", line 230, in dumps
themotte    |     return json.dumps(obj, **kwargs)
themotte    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
themotte    |   File "/usr/local/lib/python3.11/json/__init__.py", line 238, in dumps
themotte    |     **kw).encode(obj)
themotte    |           ^^^^^^^^^^^
themotte    |   File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode
themotte    |     chunks = self.iterencode(o, _one_shot=True)
themotte    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
themotte    |   File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode
themotte    |     return _iterencode(o, 0)
themotte    |            ^^^^^^^^^^^^^^^^^
themotte    | ValueError: Circular reference detected
```

**Comment by justcool393** [comment]
duplicate of #277
